[package]
name = "vtui"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1.0"
crossterm = {  version = "0.28", features = ["event-stream"]}
futures = "0.3"
tokio.workspace = true
ratatui = {  version = "0.29" , features = ["crossterm"]}
vim_rs.workspace = true
vim_macros.workspace = true
chrono = "0.4"
tui-tree-widget = "0.23"
serde_json.workspace = true
log.workspace = true
simplelog = "0.12"
indexmap.workspace = true
thiserror.workspace = true
