[package]
name = "vim_macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Rust Binding MAcros for the VMware by Broadcom vCenter VI JSON API"
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/vim_macros"
keywords = ["vi-json", "vim", "vcenter", "vmware", "macros"]
categories = ["api-bindings", "network-programming"]
exclude = ["target/*", "**/*.rs.bk"]

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
thiserror.workspace = true
phf.workspace = true
