[package]
name = "macro_examples"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "retrieve_host_info"
path = "src/retrieve_host_info.rs"

[[bin]]
name = "retrieve_ds_hosts"
path = "src/retrieve_ds_hosts.rs"

[[bin]]
name = "vm_events"
path = "src/vm_events.rs"

[[bin]]
name = "print_vm_addresses"
path = "src/print_vm_addresses.rs"

[[bin]]
name = "retrieve_recent_task"
path = "src/retrieve_recent_task.rs"

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
tokio.workspace = true
utils = { version = "0.1.0", path = "../utils" }
vim_rs.workspace = true
vim_macros.workspace = true
log.workspace = true
